#/etc/loki/loki-config.yaml
 server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
  log_level: info

auth_enabled: false   # disable multi-tenant auth

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /var/loki/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /var/loki/chunks

compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 5m

limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_entries_limit_per_query: 5000
  max_streams_per_user: 10000
  reject_old_samples: true
  retention_period: 168h   # 7 days retention

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
